DROP TABLE IF EXISTS PRODUCT_SELLER;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS BRAND;
DROP TABLE IF EXISTS COLOR;
DROP TABLE IF EXISTS PRODUCT_CATEGORY;
DROP TABLE IF EXISTS SIZE;
DROP TABLE IF EXISTS SELLER;

CREATE TABLE BRAND (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

CREATE TABLE COLOR (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

CREATE TABLE SIZE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  code VARCHAR(250) NOT NULL
);

CREATE TABLE PRODUCT_CATEGORY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

CREATE TABLE PRODUCT(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  PRODUCT_CATEGORY_ID INT NOT NULL,
  foreign key (PRODUCT_CATEGORY_ID) references PRODUCT_CATEGORY(ID)
);

CREATE TABLE SELLER (
   id INT AUTO_INCREMENT  PRIMARY KEY,
   SELLER_NAME VARCHAR(250) NOT NULL
  );

CREATE TABLE PRODUCT_SELLER (
  PRODUCT_SELLER_ID INT AUTO_INCREMENT  PRIMARY KEY,
  QUANTITY INT NOT NULL,
  PRICE DOUBLE NOT NULL,
  SKU VARCHAR(250) NOT NULL,
  PRODUCT_ID INT NOT NULL,
  foreign key (PRODUCT_ID) references PRODUCT(id),
  SELLER_ID INT NOT NULL,
  foreign key (SELLER_ID) references SELLER(id),
  BRAND_ID INT NOT NULL,
  foreign key (BRAND_ID) references BRAND(ID),
  COLOR_ID INT NOT NULL,
  foreign key (COLOR_ID) references COLOR(ID),
  SIZE_ID INT NOT NULL,
  foreign key (SIZE_ID) references SIZE(ID)
  );